/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.controllers.db.WhatWebDBKud;
import ehu.isad.controllers.ui.CMSKud;
import ehu.isad.controllers.ui.MainKud;
import ehu.isad.controllers.ui.ServerKud;
import ehu.isad.controllers.ui.WhatWebKud;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Callback;

import java.io.IOException;

public class WhatWeb extends Application {

    private Parent mainUI;
    private Parent cmsUI;
    private Parent serverUI;
    private Parent whatwebUI;

    private static Stage stage;
    private static Scene scene;

    private MainKud mainKud;
    private CMSKud cmsKud;
    private ServerKud serverKud;
    private WhatWebKud whatwebKud;

    private double xOffset = 0;
    private double yOffset = 0;

    public static void main(String[] args) {
        launch();
    }

    public static Stage getStage() {
        return stage;
    }

    public static Scene getScene() {
        return scene;
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        stage.setResizable(false);
        stage.initStyle(StageStyle.UNDECORATED);
        this.mainErakutsi();
        cmsKud.gaituTaulaEventFilter();
        cmsKud.gaituTxtURLEventFilter();
        serverKud.gaituListHistorialaEventFilter();
        whatwebKud.gaituTxtURLEventFilter();
    }

    private void mainErakutsi() throws IOException {
        this.pantailakKargatu();

        //Leihoa mugitu ahal izateko
        mainUI.setOnMousePressed(event -> {
            xOffset = event.getSceneX();
            yOffset = event.getSceneY();
        });
        mainUI.setOnMouseDragged(event -> {
            stage.setX(event.getScreenX() - xOffset);
            stage.setY(event.getScreenY() - yOffset);
        });

        scene = new Scene(mainUI);
        stage.setScene(scene);
        stage.show();
    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderMain = new FXMLLoader(getClass().getResource("/Main.fxml"));

        //Hau ez dakit zertarako egin behar den
        mainKud = new MainKud(/*this*/);

        cmsKud = new CMSKud(this);
        serverKud = new ServerKud(this);
        whatwebKud = new WhatWebKud(this);

        Callback<Class<?>, Object> controllerFactory = type -> {
            if (type == MainKud.class) {
                return mainKud;
            } else if (type == CMSKud.class) {
                return cmsKud;
            } else if (type == ServerKud.class) {
                return serverKud;
            } else if (type == WhatWebKud.class) {
                return whatwebKud;
            } else {
                try {
                    return type.newInstance();
                } catch (Exception e) {
                    e.printStackTrace();
                    throw new RuntimeException(e);
                }
            }
        };

        loaderMain.setControllerFactory(controllerFactory);

        mainUI = (Parent) loaderMain.load();
    }

    public void serverPantailaEguneratu() {
        serverKud.eguneratu();
    }

    public void aktibatuCMS() {
        cmsKud.aktibatuCMS();
    }

    public void aktibatuServer() {
        serverKud.aktibatuServer();
    }

    public void aktibatuWhatWeb() {
        whatwebKud.aktibatuWhatWeb();
    }

    public void desaktibatuCMS() {
        cmsKud.desaktibatuCMS();
    }

    public void desaktibatuServer() {
        serverKud.desaktibatuServer();
    }

    public void desaktibatuWhatWeb() {
        whatwebKud.desaktibatuWhatWeb();
    }

    public void urlEguneratu(String selectedItem) {
        mainKud.erakutsiWhatWeb();
        whatwebKud.urlEguneratu(selectedItem);
    }

    public static boolean inHierarchy(Node node, Node potentialHierarchyElement) {
        if (potentialHierarchyElement == null) {
            return true;
        }
        while (node != null) {
            if (node == potentialHierarchyElement) {
                return true;
            }
            node = node.getParent();
        }
        return false;
    }
}
